### PR TITLE
added ciphers

### PR DESCRIPTION
**Pull request by JamesBelchamber**
I had some problems with ciphers not included on the list. I would prefer to remove this option entirely, but if someone is using them I guess they should stay.

### CODE REVIEW

**Comment by agronaught** [comment]
I'm cool with this, however...

What version of OS/SSH are you running ?

**Comment by agronaught** [comment]
Thanks for the updates.  I've merged and uploaded to puppetforge.

We do need to fix the spec tests to match the ciphers change, I'll try and
get to that tonight.

Cheers
Jason.

On Tue, Jan 27, 2015 at 8:40 AM, James Belchamber notifications@github.com
wrote:

> I had some problems with ciphers not included on the list. I would prefer
> to remove this option entirely, but if someone is using them I guess they
> 
> ## should stay.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/agronaught/puppet-autossh/pull/7
> Commit Summary
> - added ciphers
> 
> File Changes
> - _M_ manifests/params.pp
>   https://github.com/agronaught/puppet-autossh/pull/7/files#diff-0 (2)
> 
> Patch Links:
> - https://github.com/agronaught/puppet-autossh/pull/7.patch
> - https://github.com/agronaught/puppet-autossh/pull/7.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agronaught/puppet-autossh/pull/7.

## 

## 

Teach your kids Science, or somebody else will :/

jason@ball.net
vk2vjb@google.com vk2flnx@google.com
callsign: vk2vjb

**Comment by JamesBelchamber** [comment]
RHEL 6.4, but with some cipher lockdown. I don't know why it's like that, but preferably it should be optional anyway (the cipher spec in the config template). I'll take a look tomorrow, as well as taking a look at the spec files :)

**Comment by agronaught** [comment]
I am curious why you didn't simply override the cipher string in the call
to the class as the override does work to customise this for other
environments.   The objective here is to allow people to use 'faster'
encryption options in environments that allow them.

class { 'autossh':
  ssh_ciphers =>
'blowfish-cbc,aes128-cbc,3des-cbc,cast128-cbc,arcfour,aes192-cbc,aes256-cbc,aes128-ctr,aes192-ctr,aes256-ctr'
}

I am considering reverting this change as the simply (faster) crypto will
be more suitable for most use cases unless specific requirements are
considered.

On Tue, Jan 27, 2015 at 9:57 AM, James Belchamber notifications@github.com
wrote:

> RHEL 6.4, but with some cipher lockdown. I don't know why it's like that,
> but preferably it should be optional anyway (the cipher spec in the config
> template). I'll take a look tomorrow, as well as taking a look at the spec
> files :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agronaught/puppet-autossh/pull/7#issuecomment-71556620
> .

## 

## 

Teach your kids Science, or somebody else will :/

jason@ball.net
vk2vjb@google.com vk2flnx@google.com
callsign: vk2vjb

**Comment by JamesBelchamber** [comment]
The ciphers are in order of preference, so the four I tacked on to the end are of little consequence. The reason I created a PR to merge this back in is so that other people won't have the same problem I did - it didn't 'just work' out of the box. If you're trying to prefer 'faster' encryption options you still need to include all of them or some people just won't get a connection.

In fact, all this is just overriding the defaults set by the OpenSSH team and the package maintainers. A 'default' Ciphers list is already in the package anyway, so I'd recommend scrapping this config entirely - or at least making it optional and off by default.

**Pull request merged**
